version: '3'

services:
  php:
    build:
      context: ./docker/php
    ports:
      - '9000'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8090:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: locations_app
      MYSQL_DATABASE: locations_app
      MYSQL_PASSWORD: secret
    ports:
      - '3312:3306'
    volumes:
      - mysql-data:/var/lib/mysql --user ${UID}
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  mysql-data:
